server:
port: 8080
spring:
datasource:
url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
driver-class-name: org.h2.Driver
username: sa
password: ""
jpa:
hibernate:
ddl-auto: none # usamos schema.sql
show-sql: true
properties:
hibernate.format_sql: true
sql:
init:
mode: always
h2:
console:
enabled: true
path: /h2-console
jackson:
serialization:
write-dates-as-timestamps: false

jwt:
secret: "test_secret_de_32_bytes_min_1234567890abcd"
expiration-minutes: 120