CREATE TABLE IF NOT EXISTS users (
id VARCHAR(36) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created TIMESTAMP NOT NULL,
modified TIMESTAMP NOT NULL,
last_login TIMESTAMP NOT NULL,
token VARCHAR(512) NOT NULL,
isactive BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS phones (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
number VARCHAR(20) NOT NULL,
citycode VARCHAR(10) NOT NULL,
countrycode VARCHAR(10) NOT NULL,
user_id VARCHAR(36) NOT NULL,
CONSTRAINT fk_phones_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);